package fr.uga.l3miage.pc.enums;

public enum EnumTechniquesAuto {
    DONNANT_DONNANT,
    DONNANT_DONNANT_ALEATOIRE,
    DONNANT_POUR_2_DONNANTS,
    DONNANT_POUR_2_DONNANTS_ET_ALEATOIRE,
    SONDEUR_NAIF,
    SONDEUR_REPENTANT,
    PACIFICATEUR,
    PACIFICATEUR_NAIF,
    ALEATOIRE,
    TJRS_TRAHIR,
    TJRS_COOP,
    RANCUNIER,
    PAVLOV,
    PAVLOV_ALEATOIRE,
    ADAPTATIF,
    GRADUEL,
    DONNANT_DONNANT_SOUPCONNEUX,
    RANCUNIER_DOUX
}
